### ISSUE TITLE
Does not skipping night

### ISSUE THREAD

**Issue by Sheridan** [jodeks-datapacks/Sleep#1]
I play alone on my home multiplayer server. But I place virtual players on farms using carpet (`run(str('player %s spawn at %f %f %f facing 0 0 in minecraft:%s', name, coordinates:0, coordinates:1, coordinates:2, dimension));`). After a recent update, the mod stopped skipping the night. The alerts remain, but the night is not skipped...

**Comment by Jodekq** [comment]
Sorry for the late reply, which version are you playing on?

**Comment by ayefliqz** [comment]
Im having the same issue but im playing on 1.20.4, apart from the fact that im using acutal players and it used to skip the night but now its no longer.

**Comment by Jodekq** [comment]
Did you change anything or added any other mods/datapacks?

**Comment by Jodekq** [comment]
I think i fixxed the issue. Please download the latest version and run `/function sleep:uinstall` to make sure everything works properly. Thanks for notifying me!
