### ISSUE TITLE
Can no longer sleep after uninstall.

### ISSUE THREAD

**Issue by M4Lfunct10n** [jodeks-datapacks/Sleep#10]
Title says it. After following uninstall instructions to remove the mod, I can no longer sleep in my world.

**Comment by Jodekq** [comment]
Im sorry for the inconvenience, I recently completely rewrite the datapack and forgot to include something in the uninstall function. 
I've uploaded a version to fix that on modrinth, but you can also just run this command:
`/gamerule playerSleepingPercentage 100`

**Comment by Zorklis** [comment]
> Im sorry for the inconvenience, I recently completely rewrite the datapack and forgot to include something in the uninstall function. I've uploaded a version to fix that on modrinth, but you can also just run this command: `/gamerule playerSleepingPercentage 100`

thanks, the command helped me solve a multiple month lasting bug (then again I did stop playing minecraft during those months)
