### ISSUE TITLE
Not skipping night with a single player on Server

### ISSUE THREAD

**Issue by ToasterUwU** [jodeks-datapacks/Sleep#2]
Just like in #1 this mod doesnt skip the night when i try to sleep as the only player that has ever been on the server.

I use the newest version on 1.21 from modrinth. I have not changed any settings or used any commands. 

Let me know if you need more info

**Comment by Jodekq** [comment]
If you do `/reload` is there a message in the chat?

**Comment by shempisk** [comment]
I am having the same issue cant sleep with mod and if I remove mod I can no longer sleep.

`/reload` shows 

`/reload
[22:38:26] [Server thread/INFO]: Reloading!
[22:38:26] [Server thread/INFO]: Loaded 1869 recipes
[22:38:27] [Server thread/INFO]: Loaded 2014 advancements
[22:38:27] [ForkJoinPool.commonPool-worker-1/INFO]: Loaded 58 translation keys`

**Comment by Jodekq** [comment]
Normally there should be a message...

I can tell you some things you can try:

run /function sleep:uninstall and then /reload 

or

run /function sleep:load

If there is no loaded message in the chat or if there is one but it still doesn't work I would suggest you download the datapack version.

The datapack is just a .zip file which you can put in the datapacks folder (most likely in your world folder)

**Comment by shempisk** [comment]
I tried the datapack option however I still can not sleep. Sleep animation starts then hangs when faded down but never actually completes sleep. Perhaps its an issue my side?

What files does the mod change, so I can try to rebuild my world file?

**Comment by Jodekq** [comment]
Did you delete the mod before putting the datapack in?
Im really sure that it works, I've tested it multiple times...

The datapack/mod does not change any files, the only thing you have to do is /function sleep:uninstall

**Comment by shempisk** [comment]
I think it's working now, perhaps I was a little hasty. Confirming the datapack is working as expected. Haven't tried the mod file.

**Comment by ToasterUwU** [comment]
Im using a different mod now that works and does everything i care about, but less than this one. Feel free to close this issue if you want, or to keep it open to find the issue and fix it.

**Comment by Jodekq** [comment]
Well, for me there is not really an issue as I can't reproduce it. I've tried it out in many different ways and it always worked as intended (the datapack and the mod). 

But if it works for you with another mod now, that's great to hear!
