### ISSUE TITLE
Weather doesn't clear after sleep

### ISSUE THREAD

**Issue by bearaujus** [jodeks-datapacks/Sleep#5]
I love some of your mods since this is not changing the vanilla things!
But on this mods I find after sleeping, the weather is not cleared

Before sleep:
![2024-09-30_01 18 12](https://github.com/user-attachments/assets/b1afce5b-556d-4952-afb5-ead7b84e0d15)

After sleep:
![2024-09-30_01 18 52](https://github.com/user-attachments/assets/c8a3f2e7-3421-426f-9d3d-f4bd75a3b977)

My init commands:
```
    - '/trigger sleep_notification set 1'
    - '/scoreboard players set &percentage_mode sleep.config 1'
    - '/scoreboard players set &percentage_to_sleep sleep.config 0'
```

**Comment by Jodekq** [comment]
Thanks for the report! This will be fixed in the next release.

**Comment by bearaujus** [comment]
Your welcome!
Also, it's a good practice to close the issue when you already implemented the feature:D
So you can like attach this issue to the commit.
