### ISSUE TITLE
Sleep text notification bug at the early morning

### ISSUE THREAD

**Issue by bearaujus** [jodeks-datapacks/Sleep#6]
Steps to reproduce:
1. Execute `/trigger sleep_notification set 1`
2. Sleep
3. As soon after you wake up (time skip), right click on the bed where you was slept
4. You will see the notification text is bugged (*The text is there, but the behavior is odd like pop-ed and pop-ed out too fast)
5. As time passed a little bit, it should be working normally again

**Comment by Jodekq** [comment]
Thats because I have to clear the title after the player slept. If I wouldn't do that, another issue would come up which is that the title is "is sleeping" without a name.
I can reproduce the issue but it's nothing to worry about, just looks a bit weird ;)
