### ISSUE TITLE
Cannot sleep at all after adding mod

### ISSUE THREAD

**Issue by Vahtera** [jodeks-datapacks/Sleep#9]
Running a self-made modpack on MC 1.20.1 / Fabric 0.15.11, using sleep 2.1.2+mod (from Modrinth,)

Added Sleep to the modpack, and now I can't sleep anymore, even if I'm the only player. 

Tried in single-player, and Open to LAN. Impossible to sleep. Just fades to the darkened screen and displays Sleeping: usernames, but won't actually skip the night.

**Comment by Jodekq** [comment]
What other mods do you use? You could also try to use the datapack instead

**Comment by Vahtera** [comment]
There's a hundred or so other mods, but the only one I can think of that could affect sleeping things is a mod that adds sleeping bags. 

I ended up just scrapping using mods altogether, since the gamerule now exist.
